### ISSUE TITLE
No description shown for @dev, @param, @return

### ISSUE THREAD

**Issue by loredanacirstea** [vitiko/solidity-doc#1]
Example:

##### Returns

|#  |Param|Type|TypeHint|Description|
|---|-----|----|--------|-----------|
|0|data|bytes32|||

For 
`/// @return Hash of the message.`

**Comment by vitiko** [comment]
fixed  https://github.com/vitiko/solidity-structure/commit/ed9fbe426f659f840972e6ff92e0194b93b08960
